# name: Continuous Delivery
 
# on:
#   pull_request:
#     branches:
#       - develop   
  
# jobs:
#     build_and_push:
#         runs-on: ubuntu-latest
#         steps:
#             -   name: Checkout
#                 uses: actions/checkout@v5
#             -   name: Login to Docker Hub
#                 uses: docker/login-action@v3
#                 with:
#                     username: 
#                     password:
#             -   name: Build and push
#                 uses: docker/build-push-action@v6
#                 with:
#                     push: true
#                     tags: samuelfialho1/gs-7-ai-work-bots:latest


name: Continuous Delivery

on: 
  pull_request:
    branches:
      - develop

jobs: 
    build_and_push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v5
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
          - name: Set up Docker Build
            uses: docker/setup-buildx-action@v3
            with:
              push: true
              tags: samuelfialho1/gs-7-ai-work-bots:latest